### PR TITLE
WIP: Wallet Management

### PR DESCRIPTION
**Pull request by sheldonth**
WIP UI design for managing wallets.

### CODE REVIEW

**Comment by yeastplume** [comment]
So great to see this! Let me know when you're happy for me to look and comment on it.

**Comment by sheldonth** [comment]
Have a look-see and let me know if you like the general direction. Needs some visual tweaks, and the ability to actually load a selected wallet from the wallet-list view yet. Just wanted to makes sure we're thinking about the same lines functionally.

**Comment by yeastplume** [comment]
Looks good, yes that seems to work as far as choosing a wallet. That select screen should probably have a link to add a wallet via file picker or create a new one, but I think you have this in mind and are going in the right direction. We might want to allow the user to 'name' wallets instead of just showing the file data, but this is a good start (we can change and evolve everything as we go). Once all the functionality to create, select, open wallets etc is in place we can step back, take an overall view and tweak workflows, but this is definitely going in the right direction!

There is code to produce table-rows in widgets/table_row.rs, but it's meant for an earlier version of iced-rs and hasn't been updated fully. Just pointing this out here as we'll need to get that updated to show stuff like the transaction log and peers in the node screen, etc.

**Comment by sheldonth** [comment]
The ability to name wallets and select a directory for them is added under the "Advanced Options" section of the wallet_setup.rs, although that really just saves their display name in grin-gui.yml. Thanks for the feedback, will keep pushing forward on this.

**Review by yeastplume — APPROVED** [review]

**Comment by yeastplume** [comment]
I know this is WIP but the whole project is WIP at the moment anyhow, just merging so as to have this as a base as I continue work

**Comment by sheldonth** [comment]
Sounds good. Thanks! Going to keep pushing forward.

**Pull request merged**
